CLOTHING_ONTOLOGY = {
    "Menswear": {
        "Business Casual": [
            "商务衬衫",
            "商务休闲裤",
            "休闲西装",
            "针织Polo衫",
            "商务休闲鞋",
        ],
        "Casual Sport": [
            "运动卫衣",
            "运动T恤",
            "运动短裤",
            "运动长裤",
            "运动夹克",
        ],
        "Workwear Outdoor": [
            "工装裤",
            "工装外套",
            "登山鞋",
            "多功能马甲",
            "防风冲锋衣",
        ],
    },
    "Womenswear": {
        "Business Casual": [
            "西装套",
            "商务衬衫",
            "半身裙",
            "修身连衣裙",
            "商务休闲鞋",
        ],
        "Casual Sport": [
            "leggings",
            "运动背心",
            "运动卫衣",
            "运动短裤",
            "运动夹克",
        ],
        "Workwear Outdoor": [
            "户外外套",
            "工装裤",
            "登山鞋",
            "防晒衣",
            "多功能马甲",
        ],
    },
}

CATEGORY_COLOR_MAPPING = {
    "Business Casual": [
        "Earth Tone",
        "Blue Gray",
        "Navy Blue",
        "Neutral Classic",
        "Subtle Warm",
    ],
    "Casual Sport": [
        "Fresh Contrast",
        "Solid Basic",
        "Vibrant Energy",
        "Pastel Sport",
        "Monochrome Active",
    ],
    "Workwear Outdoor": [
        "Army Green",
        "Dark Durable",
        "Earth Tone",
        "Camo Tone",
        "Rust Brown",
    ],
}

COLOR_TAG_MAPPING = {
    "大地色": "Earth Tone",
    "卡其色": "Earth Tone",
    "燕麦色": "Earth Tone",
    "驼色": "Earth Tone",
    "棕色": "Earth Tone",
    "蓝灰色": "Blue Gray",
    "灰蓝色": "Blue Gray",
    "雾蓝色": "Blue Gray",
    "深蓝色": "Navy Blue",
    "藏青色": "Navy Blue",
    "海军蓝": "Navy Blue",
    "军绿色": "Army Green",
    "橄榄绿": "Army Green",
    "墨绿色": "Army Green",
    "黑色": "Solid Basic",
    "白色": "Solid Basic",
    "纯黑": "Solid Basic",
    "纯白": "Solid Basic",
    "米白色": "Neutral Classic",
    "浅灰色": "Neutral Classic",
    "深灰色": "Neutral Classic",
    "灰色": "Neutral Classic",
    "暖灰色": "Subtle Warm",
    "奶茶色": "Subtle Warm",
    "杏色": "Subtle Warm",
    "荧光绿": "Fresh Contrast",
    "亮橙色": "Fresh Contrast",
    "柠檬黄": "Fresh Contrast",
    "电光蓝": "Fresh Contrast",
    "活力红": "Vibrant Energy",
    "亮粉色": "Vibrant Energy",
    "明黄色": "Vibrant Energy",
    "薄荷绿": "Pastel Sport",
    "淡粉色": "Pastel Sport",
    "浅蓝色": "Pastel Sport",
    "薰衣草紫": "Pastel Sport",
    "全黑": "Monochrome Active",
    "全灰": "Monochrome Active",
    "迷彩色": "Camo Tone",
    "丛林迷彩": "Camo Tone",
    "沙漠迷彩": "Camo Tone",
    "铁锈红": "Rust Brown",
    "砖红色": "Rust Brown",
    "深棕色": "Dark Durable",
    "炭灰色": "Dark Durable",
    "墨黑色": "Dark Durable",
    "暗夜色": "Dark Durable",
}

MATERIAL_TAG_MAPPING = {
    "棉麻": "Cotton Linen Blend",
    "棉麻混纺": "Cotton Linen Blend",
    "亚麻棉": "Cotton Linen Blend",
    "真丝混纺": "Silk Blend",
    "丝棉混纺": "Silk Blend",
    "丝绸混纺": "Silk Blend",
    "速干": "Quick Dry",
    "速干面料": "Quick Dry",
    "快干": "Quick Dry",
    "透气网布": "Breathable Mesh",
    "网眼布": "Breathable Mesh",
    "透气面料": "Breathable Mesh",
    "帆布": "Canvas",
    "帆布面料": "Canvas",
    "粗帆布": "Canvas",
    "防水涂层": "Waterproof Coating",
    "防水面料": "Waterproof Coating",
    "防水材质": "Waterproof Coating",
    "纯棉": "Pure Cotton",
    "全棉": "Pure Cotton",
    "精梳棉": "Pure Cotton",
    "羊毛": "Wool",
    "美利奴羊毛": "Wool",
    "羊绒": "Cashmere",
    "羊绒混纺": "Cashmere Blend",
    "涤纶": "Polyester",
    "聚酯纤维": "Polyester",
    "尼龙": "Nylon",
    "锦纶": "Nylon",
    "弹力纤维": "Elastane",
    "氨纶": "Elastane",
    "莱卡": "Elastane",
    "抓绒": "Fleece",
    "摇粒绒": "Fleece",
    "法兰绒": "Flannel",
    "灯芯绒": "Corduroy",
    "牛仔布": "Denim",
    "牛皮": "Genuine Leather",
    "真皮": "Genuine Leather",
    "合成革": "Synthetic Leather",
    "人造革": "Synthetic Leather",
    "防风面料": "Windproof Fabric",
    "防风材质": "Windproof Fabric",
    "保暖填充": "Insulated Fill",
    "羽绒填充": "Insulated Fill",
    "鹅绒": "Down Fill",
    "鸭绒": "Down Fill",
}

DESIGN_TAG_MAPPING = {
    "简约刺绣": "Minimal Embroidery",
    "小刺绣": "Minimal Embroidery",
    "精致刺绣": "Minimal Embroidery",
    "机能拉链": "Functional Zipper",
    "多功能拉链": "Functional Zipper",
    "实用拉链": "Functional Zipper",
    "反光条": "Reflective Strip",
    "反光设计": "Reflective Strip",
    "反光元素": "Reflective Strip",
    "多口袋": "Multi Pocket",
    "多功能口袋": "Multi Pocket",
    "立体口袋": "Multi Pocket",
    "加固缝线": "Reinforced Stitching",
    "双线缝制": "Reinforced Stitching",
    "加强缝线": "Reinforced Stitching",
    "可调节袖口": "Adjustable Cuff",
    "魔术贴袖口": "Adjustable Cuff",
    "可拆卸帽": "Detachable Hood",
    "连帽设计": "Hooded Design",
    "帽衫": "Hooded Design",
    "立领设计": "Stand Collar",
    "翻领设计": "Lapel Collar",
    "圆领设计": "Crew Neck",
    "V领设计": "V Neck",
    "拉链开合": "Zip Closure",
    "纽扣开合": "Button Closure",
    "套头设计": "Pullover Design",
    "抽绳设计": "Drawstring Design",
    "松紧腰": "Elastic Waist",
    "弹力腰": "Elastic Waist",
    "防泼水": "Water Resistant",
    "拒水处理": "Water Resistant",
    "透气设计": "Ventilated Design",
    "透气孔": "Ventilated Design",
    "拼接设计": "Color Block",
    "撞色设计": "Color Block",
    "印花设计": "Print Design",
    "图案印花": "Print Design",
    "格纹设计": "Plaid Pattern",
    "条纹设计": "Stripe Pattern",
}

FIT_TAG_MAPPING = {
    "修身": "Slim Fit",
    "合身": "Slim Fit",
    "修身版型": "Slim Fit",
    "直筒": "Straight Fit",
    "常规版型": "Straight Fit",
    "标准版型": "Straight Fit",
    "宽松": "Loose Fit",
    "宽松版型": "Loose Fit",
    "oversize": "Oversized",
    "超大版型": "Oversized",
    "oversized": "Oversized",
    "多调节设计": "Adjustable Design",
    "可调节版型": "Adjustable Design",
    "弹力版型": "Stretch Fit",
    "弹力修身": "Stretch Fit",
    "高腰": "High Rise",
    "高腰版型": "High Rise",
    "中腰": "Mid Rise",
    "低腰": "Low Rise",
    "短款": "Cropped",
    "短版": "Cropped",
    "加长版": "Extended Length",
    "长款": "Extended Length",
}

VALID_STANDARDIZED_TAGS = {
    "color": set(CATEGORY_COLOR_MAPPING.get("Business Casual", [])
                + CATEGORY_COLOR_MAPPING.get("Casual Sport", [])
                + CATEGORY_COLOR_MAPPING.get("Workwear Outdoor", [])),
    "material": set(MATERIAL_TAG_MAPPING.values()),
    "design": set(DESIGN_TAG_MAPPING.values()),
    "fit": set(FIT_TAG_MAPPING.values()),
}

GENDER_KEYWORDS = {
    "Menswear": ["男", "男士", "男式", "men", "mens", "male", "boys"],
    "Womenswear": ["女", "女士", "女式", "women", "womens", "female", "girls"],
}

CATEGORY_KEYWORDS = {
    "Business Casual": [
        "商务", "正装", "通勤", "办公", "衬衫", "西装", "西裤",
        "polo", "针织", "职业", "formal", "office", "business",
    ],
    "Casual Sport": [
        "休闲", "运动", "卫衣", "T恤", "短裤", "跑步", "健身",
        "casual", "sport", "athletic", "gym", "running", "hoodie",
    ],
    "Workwear Outdoor": [
        "工装", "户外", "登山", "冲锋", "防风", "防水", "多功能",
        "workwear", "outdoor", "hiking", "tactical", "cargo",
    ],
}

SUB_CATEGORY_KEYWORDS = {
    "商务衬衫": ["商务衬衫", "正装衬衫", "dress shirt"],
    "商务休闲裤": ["商务休闲裤", "西裤", "chino", "slacks"],
    "休闲西装": ["休闲西装", "blazer", "sport coat"],
    "针织Polo衫": ["polo", "针织polo", "polo衫"],
    "商务休闲鞋": ["商务鞋", "乐福鞋", "loafer", "oxford"],
    "运动卫衣": ["卫衣", "hoodie", "运动卫衣", "sweatshirt"],
    "运动T恤": ["运动T恤", "运动衫", "sports tee", "athletic shirt"],
    "运动短裤": ["运动短裤", "跑步短裤", "athletic shorts"],
    "运动长裤": ["运动长裤", "jogger", "track pants"],
    "运动夹克": ["运动夹克", "运动外套", "sports jacket", "windbreaker"],
    "工装裤": ["工装裤", "cargo pants", "cargo"],
    "工装外套": ["工装外套", "工装夹克", "work jacket", "chore coat"],
    "登山鞋": ["登山鞋", "hiking boots", "hiking shoes"],
    "多功能马甲": ["马甲", "多功能马甲", "vest", "utility vest"],
    "防风冲锋衣": ["冲锋衣", "防风衣", "shell jacket", "windbreaker"],
    "西装套": ["西装套", "套装", "suit set", "pantsuit"],
    "半身裙": ["半身裙", "skirt"],
    "修身连衣裙": ["连衣裙", "dress"],
    "leggings": ["leggings", "瑜伽裤", "yoga pants", "紧身裤"],
    "运动背心": ["运动背心", "sports bra", "tank top"],
    "户外外套": ["户外外套", "outdoor jacket", "户外夹克"],
    "防晒衣": ["防晒衣", "sun protection", "UV protection"],
}
